INSERT INTO ADDRESS(street, city, state, zip) VALUES('Al. Szucha Jana Chrystiana 1038', 'Warszawa', 'Polska', '00-582');
INSERT INTO ADDRESS(street, city, state, zip) VALUES('ul. Bracka 84', 'Tarnowskie Góry', 'Polska', '42-605');
INSERT INTO ADDRESS(street, city, state, zip) VALUES('ul. Ratajczaka Franciszka 90', 'Szczecin', 'Polska', '61-816');
INSERT INTO ADDRESS(street, city, state, zip) VALUES('ul. Projektowa 142', 'Katowice', 'Polska', '91-493');
INSERT INTO ADDRESS(street, city, state, zip) VALUES('ul. Tymiankowa 57', 'Lublin', 'Polska', '20-221');
INSERT INTO ADDRESS(street, city, state, zip) VALUES('ul. Zgierska 27', 'Łódź', 'Polska', '91-468');
INSERT INTO STUDENT(name, surname, age, address_id) VALUES('Adam', 'Nowak', 18, 1);
INSERT INTO STUDENT(name, surname, age, address_id) VALUES('Bartosz', 'Pawlak', 20, 2);
INSERT INTO STUDENT(name, surname, age, address_id) VALUES('Kinga', 'Kowalczyk', 21, 3);
INSERT INTO STUDENT(name, surname, age, address_id) VALUES('Wiktor', 'Kowalski', 20, 4);
INSERT INTO STUDENT(name, surname, age, address_id) VALUES('Piotr', 'Szczepański', 22, 5);
INSERT INTO STUDENT(name, surname, age, address_id) VALUES('Filip', 'Chmielewski', 19, 6);